# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_title', models.CharField(max_length=50)),
                ('topic_text', models.TextField()),
                ('topic_pub_date', models.DateTimeField(verbose_name='date published')),
                ('topic_resume', models.TextField()),
                ('topic_likes', models.IntegerField()),
                ('topic_image_url', models.TextField()),
            ],
        ),
    ]
