# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='topic_seo_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='topic_seo_keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='topic_seo_title',
            field=models.TextField(blank=True),
        ),
    ]
